export const API_BASE_URL = window.__RUNTIME_CONFIG__?.VITE_API_BASE_URL;
export const DOCUMENT_SIZE_LIMIT =
  window.__RUNTIME_CONFIG__?.VITE_DOCUMENT_SIZE_LIMIT;
export const DEVICE = window.__RUNTIME_CONFIG__?.VITE_DEVICE;
